name: openvisu_repository
description: A Dart Package wich provides the OpenVisu models and repositories.
version: 0.0.1
homepage: https://github.com/OpenVisu/openvisu_repository

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  localstorage: ^4.0.0+1
  universal_html: ^2.0.8
  sentry_flutter: ^6.0.0
  equatable: ^2.0.3
  logging: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
